// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIGURED, SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from './config';

/**
 * True when Supabase credentials are present in the environment.
 * When false, the app runs in local mode: auth is bypassed, edge functions
 * are skipped, and the dashboard loads directly without a login wall.
 */
export { SUPABASE_CONFIGURED } from './config';

let supabasePromise: Promise<SupabaseClient<Database>> | null = null;

export async function getSupabaseClient(): Promise<SupabaseClient<Database>> {
  if (!SUPABASE_CONFIGURED || !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error('Supabase not configured');
  }

  if (supabasePromise === null) {
    const url = SUPABASE_URL;
    const key = SUPABASE_PUBLISHABLE_KEY;
    supabasePromise = Promise.resolve(
      createClient<Database>(url, key, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    );
  }

  return supabasePromise;
}
